# use like this
# vcs 	            CLEAN, UNTRACKED, MODIFIED
# host 	            LOCAL, REMOTE
# user 	            DEFAULT, SUDO, ROOT
# context 	        DEFAULT, ROOT, SUDO, REMOTE, REMOTE_SUDO
# dir 	            HOME, HOME_SUBFOLDER, DEFAULT, ETC
# POWERLEVEL9K_VCS_CLEAN_FOREGROUND='blue'
# POWERLEVEL9K_VCS_CLEAN_BACKGROUND='black'
# POWERLEVEL9K_<segment>_<state>_[BACKGROUND|FOREGROUND]=''

# prompt currently look like:
#$echo $POWERLEVEL9K_LEFT_PROMPT_ELEMENTS
                                            #$echo $POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS
#(context dir vcs)                          (status root_indicator background_jobs history time)
#POWERLEVEL9K_MODE="CodeNewRoman Nerd Font Mono"


POWERLEVEL9K_TIME_FOREGROUND='plum1'
POWERLEVEL9K_TIME_BACKGROUND='grey11'

#context (left 1)
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='chartreuse1'
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='grey15'
POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND='lightcoral'
POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND='navyblue'
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND='red1'
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_BACKGROUND='white'

# sudo runs for one operation - prompt doesn't change when typing it in and next prompt is back at my user... what is the point?
POWERLEVEL9K_CONTEXT_SUDO_FOREGROUND='deeppink1'
POWERLEVEL9K_CONTEXT_SUDO_BACKGROUND='grey15'

# if I sudo su up - I lose the custom propmt anyway...
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='lightred'
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND='grey15'


#dir (left 2)
#HOME, HOME_SUBFOLDER, DEFAULT, ETC
POWERLEVEL9K_DIR_HOME_FOREGROUND='grey3'
POWERLEVEL9K_DIR_HOME_BACKGROUND='deeppink1'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='grey3'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='hotpink'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='grey3'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='107'
POWERLEVEL9K_DIR_ETC_FOREGROUND='grey3'
POWERLEVEL9K_DIR_ETC_BACKGROUND='087'

#vcs (left 3)
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='white'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='064'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='white'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='166'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='white'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='125'

#status (right 1)
POWERLEVEL9K__FOREGROUND='lightred'
POWERLEVEL9K__BACKGROUND='grey15'

#root_indicator  (right 2)
POWERLEVEL9K__FOREGROUND='lightred'
POWERLEVEL9K__BACKGROUND='grey15'

#background_jobs (right 3)
POWERLEVEL9K__FOREGROUND='lightred'
POWERLEVEL9K__BACKGROUND='grey15'

#history (right 4)
POWERLEVEL9K__FOREGROUND='lightred'
POWERLEVEL9K__BACKGROUND='grey15'

#time (right 5)

POWERLEVEL9K__FOREGROUND='lightred'
POWERLEVEL9K__BACKGROUND='grey15'
