# Don't print a new line at the start of the prompt
add_newline = false

format = """\
  $username\
  $hostname\
  $kubernetes\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $docker_context\
  $package\
  $dotnet\
  $golang\
  $java\
  $nodejs\
  $php\
  $python\
  $rust\
  $zig\
  $memory_usage\
  $env_var\
  $cmd_duration\
  $status\
  $custom\
  $jobs\
  $line_break\
  $time\
  $character\
  """

[username]
show_always = false

[time]
disabled = false
format = "[$time](fg:purple)"
time_format = "%T"

[package]
disabled = true

[cmd_duration]
min_time = 100
format = "| [slow: $duration]($style) "
style = "fg:purple"

[status]
disabled = false
format = "| [error: $symbol $status]($style) "

[kubernetes]
symbol = "⛵ "
style = "dimmed green"
disabled = false

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[nodejs]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "
